#!/usr/bin/Rscript

#-- input
arg=commandArgs(TRUE)
res=read.table(arg[[1]], header=TRUE, sep=',', check.names=FALSE)

#-- main
sample=res[1,1]
print("sample")
print(sample)
#sample=substr(sample,1,unlist(gregexpr('X', sample))[1]-1)
res=res[,-1]
print("res")
print(res)
#first=paste(gsub('\\.',' ', colnames(res[order(t(res),decreasing=TRUE)[1]])), res[order(t(res),decreasing=TRUE)[1]], sep='\t')
#first=paste(colnames(res[order(t(res),decreasing=TRUE)[1]]), res[order(t(res),decreasing=TRUE)[1]], sep='\t')
print("t(res)")
print(t(res))
print("t(res)[1]")
print(t(res)[1])
first=t(res)[1]

#second=paste(gsub('\\.',' ', colnames(res[order(t(res),decreasing=TRUE)[2]])), res[order(t(res),decreasing=TRUE)[2]], sep='\t')
#second=paste(colnames(res[order(t(res),decreasing=TRUE)[2]]), res[order(t(res),decreasing=TRUE)[2]], sep='\t')
second=t(res)[2]

#third=paste(gsub('\\.',' ', colnames(res[order(t(res),decreasing=TRUE)[3]])), res[order(t(res),decreasing=TRUE)[3]], sep='\t')
#third=paste(colnames(res[order(t(res),decreasing=TRUE)[3]]), res[order(t(res),decreasing=TRUE)[3]], sep='\t')
third=t(res)[3]

fourth=t(res)[4]

phrase3=paste("transcuptomics_knn", sample, first, second, NA, NA, NA, NA, sep="\t")
phrase2=paste("transcuptomics_rf", sample, third, fourth, NA, NA, NA, NA, sep="\t")
phrase1=paste("method", "sample","pred1","prob1","pred2","prob2","pred3","prob3",sep='\t')

#-- output
output=arg[[2]]
write.table(rbind(phrase1,phrase2,phrase3),output, quote=FALSE, col.names=FALSE, row.names=FALSE, sep='\t')
