#!/usr/bin/Rscript

#-- input
arg=commandArgs(TRUE)
res=read.table(arg[[1]], header=TRUE, sep='\t')

#-- main
sample=res$sample_name[1]
#sample=substr(sample,1,unlist(gregexpr('X', sample))[1]-1)
res=res[,c(2,3)]
res=res[order(res$pred,decreasing=TRUE),][seq(1,3),]
phrase=paste(sample,res[1,1],res[1,2],res[2,1],res[2,2],res[3,1],res[3,2],sep='\t')
phrase1=paste("sample","pred1","prob1","pred2","prob2","pred3","prob3",sep='\t')

#-- output
output=arg[[2]]
write.table(rbind(phrase1,phrase),output, quote=FALSE, col.names=FALSE, row.names=FALSE, sep='\t')


